CREATE DATABASE emplo;
USE emplo;
CREATE TABLE emtb(E_ID VARCHAR(20) NOT NULL,E_NAME VARCHAR(20) NOT NULL,AGE INT(3) NOT NULL,SALARY INT(20) NOT NULL); INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("101","ANU","22","9000");
INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("102","SHANE","29","8000");
INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("103","ROHAN","34","6000");
INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("104","SCOTT","44","10000");
INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("105","TIGER","35","8000");
INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("106","ALEX","27","7000");
INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("107","ABHI","29","8000");
select E_NAME,SALARY,designation(SALARY) from emtb;


#functions
CREATE DEFINER=`root`@`localhost` FUNCTION `designation`(salary int(20)) RETURNS varchar(11) CHARSET latin1
BEGIN
if(SALARY>40000)
then
return ("senior employee");
else
return ("junior employee");
end if;
END
